### PR TITLE
creating a unit test to trap a bug with parametric bootstrap fixes #154

### LINKED ISSUE #154: Is On Range for Sample of a Parametric Bootstrap seems to improperly validate
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/9c2afd69834295260fb07c7ff1efeae8a951a4cc/Statistics/Distributions/IDistributionExtensions.cs#L29

i think it should have a bang in front, to evaluate if it is not in range.

### PR DESCRIPTION
**Pull request by HenryGeorgist**

### CODE REVIEW

File: StatisticsTests/Distributions/ParametricBootstrap.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+namespace StatisticsTests.Distributions
+{
+    public class ParametricBootstrap
+    {
+        [Theory]
+        [InlineData(0, 1d, 100)]
+        public void Bootstrap_Works_with_Reasonable_RandomRange(double min, double max, int n)
+        {
+            Statistics.Distributions.Uniform dist = new Statistics.Distributions.Uniform(min, max, n);
+            double[] randyPacket = new double[dist.SampleSize];//needs to be initialized with a set of random nubmers between 0 and 1;
```
Comment (rnugent3) [inline StatisticsTests/Distributions/ParametricBootstrap.cs:18]: is packet a common programming term?

File: StatisticsTests/Distributions/ParametricBootstrap.cs [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+            for (int i = 0; i < dist.SampleSize; i++)
+            {
+                randyPacket[i] = ((double)i +0.5) / (double)dist.SampleSize;
+            }
+            Statistics.IDistribution bootstrap = dist.Sample(randyPacket);
+            Assert.Equal(bootstrap.Mean, .5);
```
Comment (rnugent3) [inline StatisticsTests/Distributions/ParametricBootstrap.cs:24]: clear test.

**Review by rnugent3 — APPROVED** [review]
Looks good.
